baseurl = "http://blog.kayodiet.com/"
languageCode = "en-us"
title = "Kayo Arima"
theme = "hugo-icarus-theme"


disqusShortname = "spf13"
googleAnalytics = ""
paginate = 10
footnotereturnlinkcontents = "↩"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    code = "http://web.masonkatz.com/"
    home = "http://www.kayodiet.com/"
    author = "Kayo Arima"
    bio = "Blogger - Programmer - Gopher"
    location = "Earth"
    site_description = ""
    copyright  = "Kayo Arima"
    avatar = "img/kayo.png"
    date_format = "2006-01-02"

[social]
    email           = "kayo.arima.katz@gmail.com"
    facebook        = "kayokatz"
    linkedin        = "kayo-arima-23358b4"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true