baseurl = "http://www.kayodiet.com/"
languageCode = "en-us"
title = "Kayo Diet"
theme = "landing"

[params]
	googleAnalytics = "UA-79556153-1"
	code = "http://web.masonkatz.com/"
#	description = "Nutritional Service"
	author = "Kayo Arima"
	location = "San Diego, CA"
	copyright  = "Kayo Arima"
	fbappid       = "1621408731502594"
	ogtitle       = "My goal is your health for life"
	ogimage       = "http://www.kayodiet.com/images/og-image.jpg"
	ogdescription = "I let you control your appetite, food choices, and everyday meals with the backing of cutting edge science. Read useful information, such as why you don’t need to count calories, what phytic acid is and more in my blog."

[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:kayo.arima.katz@gmail.com"


