baseurl = "http://www.kayodiet.com/"
languageCode = "en-us"
title = "Kayo Diet"
theme = "landing"

[params]
	googleAnalytics = "UA-79556153-1"
	code = "http://web.masonkatz.com/"
	description = "Nutritional Service"
	author = "Kayo Arima"
	location = "San Diego, CA"
	site_description = ""
	copyright  = "Kayo Arima"

[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:kayo.arima.katz@gmail.com"


